"""user scopes

Revision ID: 487a048f12b5
Revises: 65cc0106f4f4
Create Date: 2024-03-21 15:47:27.274330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '487a048f12b5'
down_revision: Union[str, None] = '65cc0106f4f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('scopes_str', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'scopes_str')
    # ### end Alembic commands ###
