"""soft delete

Revision ID: 9a88b5faf009
Revises: 487a048f12b5
Create Date: 2024-03-27 21:55:11.092134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a88b5faf009'
down_revision: Union[str, None] = '487a048f12b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_messages_deleted'), 'messages', ['deleted'], unique=False)
    op.add_column('threads', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_threads_deleted'), 'threads', ['deleted'], unique=False)
    op.add_column('users', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_users_deleted'), 'users', ['deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted'), table_name='users')
    op.drop_column('users', 'deleted')
    op.drop_index(op.f('ix_threads_deleted'), table_name='threads')
    op.drop_column('threads', 'deleted')
    op.drop_index(op.f('ix_messages_deleted'), table_name='messages')
    op.drop_column('messages', 'deleted')
    # ### end Alembic commands ###
